"""create notification_recipients

Revision ID: 029d8955ef81
Revises: a80b5afbcd91
Create Date: 2026-01-19 17:26:09.469900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '029d8955ef81'
down_revision = 'a80b5afbcd91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_recipients',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'email', name='uq_recipient_user_email')
    )
    with op.batch_alter_table('notification_recipients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_recipients_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_recipients_user_enabled', ['user_id', 'enabled'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification_recipients', schema=None) as batch_op:
        batch_op.drop_index('ix_recipients_user_enabled')
        batch_op.drop_index(batch_op.f('ix_notification_recipients_user_id'))

    op.drop_table('notification_recipients')
    # ### end Alembic commands ###
