"""cria tabela custos_fixos_pagamentos

Revision ID: 08999af2edf9
Revises: 6083b5cc613d
Create Date: 2026-01-14 19:32:59.510462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08999af2edf9'
down_revision = '6083b5cc613d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custos_fixos_pagamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('custo_fixo_id', sa.Integer(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('pago_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['custo_fixo_id'], ['custos_fixos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('custo_fixo_id', 'ano', 'mes', name='uq_custo_fixo_mes')
    )
    with op.batch_alter_table('custos_fixos_pagamentos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_custos_fixos_pagamentos_ano'), ['ano'], unique=False)
        batch_op.create_index(batch_op.f('ix_custos_fixos_pagamentos_custo_fixo_id'), ['custo_fixo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_custos_fixos_pagamentos_mes'), ['mes'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('custos_fixos_pagamentos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_custos_fixos_pagamentos_mes'))
        batch_op.drop_index(batch_op.f('ix_custos_fixos_pagamentos_custo_fixo_id'))
        batch_op.drop_index(batch_op.f('ix_custos_fixos_pagamentos_ano'))

    op.drop_table('custos_fixos_pagamentos')
    # ### end Alembic commands ###
