"""cria tabela amazon_credentials

Revision ID: 0eed9d9ae7c9
Revises: 4d60d85f720c
Create Date: 2026-01-14 17:14:25.734541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0eed9d9ae7c9'
down_revision = '4d60d85f720c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('amazon_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.String(length=50), nullable=True),
    sa.Column('client_id', sa.String(length=200), nullable=True),
    sa.Column('client_secret', sa.String(length=200), nullable=True),
    sa.Column('refresh_token', sa.String(length=500), nullable=True),
    sa.Column('marketplace_region', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('amazon_credentials')
    # ### end Alembic commands ###
