"""add dia_pagamento em custos_fixos

Revision ID: 6083b5cc613d
Revises: af6111cdc094
Create Date: 2026-01-14 18:17:50.675633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6083b5cc613d'
down_revision = 'af6111cdc094'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('custos_fixos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dia_pagamento', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('custos_fixos', schema=None) as batch_op:
        batch_op.drop_column('dia_pagamento')

    # ### end Alembic commands ###
