"""cria custos_fixos

Revision ID: af6111cdc094
Revises: fa645213f28e
Create Date: 2026-01-14 17:38:11.418199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af6111cdc094'
down_revision = 'fa645213f28e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custos_fixos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('categoria', sa.String(length=60), nullable=False),
    sa.Column('valor_mensal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('custos_fixos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_custos_fixos_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('custos_fixos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_custos_fixos_user_id'))

    op.drop_table('custos_fixos')
    # ### end Alembic commands ###
