"""add notification settings and log

Revision ID: d847c2b92ad1
Revises: 08999af2edf9
Create Date: 2026-01-16 16:43:44.179914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd847c2b92ad1'
down_revision = '08999af2edf9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_settings',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('alert_mode', sa.String(length=32), nullable=False),
    sa.Column('days_before', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notification_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_settings_user_id'), ['user_id'], unique=True)

    op.create_table('notification_log',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('custo_fixo_id', sa.BigInteger(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('alert_type', sa.String(length=16), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['custo_fixo_id'], ['custos_fixos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'custo_fixo_id', 'ano', 'mes', 'alert_type', name='uq_notification_dedupe')
    )
    with op.batch_alter_table('notification_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_log_custo_fixo_id'), ['custo_fixo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_log_sent_at'), ['sent_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_log_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('custos_fixos_history', schema=None) as batch_op:
        batch_op.alter_column('action',
               existing_type=sa.TEXT(),
               type_=sa.String(length=32),
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('idx_cfh_changed_at'))
        batch_op.drop_index(batch_op.f('idx_cfh_changed_by'))
        batch_op.drop_index(batch_op.f('idx_cfh_item_id'))
        batch_op.create_index(batch_op.f('ix_custos_fixos_history_changed_at'), ['changed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_custos_fixos_history_changed_by'), ['changed_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_custos_fixos_history_item_id'), ['item_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('custos_fixos_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_custos_fixos_history_item_id'))
        batch_op.drop_index(batch_op.f('ix_custos_fixos_history_changed_by'))
        batch_op.drop_index(batch_op.f('ix_custos_fixos_history_changed_at'))
        batch_op.create_index(batch_op.f('idx_cfh_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_cfh_changed_by'), ['changed_by'], unique=False)
        batch_op.create_index(batch_op.f('idx_cfh_changed_at'), [sa.literal_column('changed_at DESC')], unique=False)
        batch_op.alter_column('action',
               existing_type=sa.String(length=32),
               type_=sa.TEXT(),
               existing_nullable=False)

    with op.batch_alter_table('notification_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_log_user_id'))
        batch_op.drop_index(batch_op.f('ix_notification_log_sent_at'))
        batch_op.drop_index(batch_op.f('ix_notification_log_custo_fixo_id'))

    op.drop_table('notification_log')
    with op.batch_alter_table('notification_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_settings_user_id'))

    op.drop_table('notification_settings')
    # ### end Alembic commands ###
