"""add api_key to users

Revision ID: f7b471d6fbca
Revises: a1b2c3d4e5f6
Create Date: 2026-05-21 23:01:24.405343

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f7b471d6fbca'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('amazon_connections', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('amazon_connections_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('amazon_financial_events', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('amazon_financial_events_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('amazon_inventory_snapshots', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('amazon_inventory_snapshots_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('amazon_order_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_public_amazon_order_items_amazon_order_id'), ['amazon_order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_public_amazon_order_items_user_id'), ['user_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('amazon_order_items_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('amazon_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_amazon_orders_amazon_order_id'))
        batch_op.drop_index(batch_op.f('ix_amazon_orders_user_id'))
        batch_op.create_index(batch_op.f('ix_public_amazon_orders_amazon_order_id'), ['amazon_order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_public_amazon_orders_user_id'), ['user_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('amazon_orders_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('amazon_sku_links', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('amazon_sku_links_user_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('amazon_sku_links_product_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'products', ['product_id'], ['id'])

    with op.batch_alter_table('custos_fixos', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)

    with op.batch_alter_table('custos_fixos_pagamentos', schema=None) as batch_op:
        batch_op.alter_column('pago_em',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('api_key', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_api_key'), ['api_key'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_api_key'))
        batch_op.drop_column('api_key')

    with op.batch_alter_table('custos_fixos_pagamentos', schema=None) as batch_op:
        batch_op.alter_column('pago_em',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)

    with op.batch_alter_table('custos_fixos', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)

    with op.batch_alter_table('amazon_sku_links', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('amazon_sku_links_product_id_fkey'), 'products', ['product_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('amazon_sku_links_user_id_fkey'), 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('amazon_orders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('amazon_orders_user_id_fkey'), 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_index(batch_op.f('ix_public_amazon_orders_user_id'))
        batch_op.drop_index(batch_op.f('ix_public_amazon_orders_amazon_order_id'))
        batch_op.create_index(batch_op.f('ix_amazon_orders_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_amazon_orders_amazon_order_id'), ['amazon_order_id'], unique=False)

    with op.batch_alter_table('amazon_order_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('amazon_order_items_user_id_fkey'), 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_index(batch_op.f('ix_public_amazon_order_items_user_id'))
        batch_op.drop_index(batch_op.f('ix_public_amazon_order_items_amazon_order_id'))

    with op.batch_alter_table('amazon_inventory_snapshots', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('amazon_inventory_snapshots_user_id_fkey'), 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('amazon_financial_events', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('amazon_financial_events_user_id_fkey'), 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('amazon_connections', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('amazon_connections_user_id_fkey'), 'users', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
