"""cripto tokens amazon_credentials

Revision ID: fa645213f28e
Revises: 0eed9d9ae7c9
Create Date: 2026-01-14 17:24:13.125602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa645213f28e'
down_revision = '0eed9d9ae7c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('amazon_credentials', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_secret_enc', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('refresh_token_enc', sa.Text(), nullable=True))
        batch_op.drop_column('client_secret')
        batch_op.drop_column('refresh_token')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('amazon_credentials', schema=None) as batch_op:
        batch_op.add_column(sa.Column('refresh_token', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('client_secret', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.drop_column('refresh_token_enc')
        batch_op.drop_column('client_secret_enc')

    # ### end Alembic commands ###
